version: "3"
services:
  python_rest:
    # replace username/repo:tag with your name and image details
    image: and_ok/flask_rest:0.1
    volumes:
      - ./service_images/data:/app/service_images/data
    ports:
      - "5000:5000"
    build: .
